services:
  app:
    build:
        context: .
        dockerfile: Dockerfile

    command:
      - --host=0.0.0.0
      - --port=9555
      - "--reload"
      - "--reload-exclude=scripts/*"
      - "--reload-exclude=tests/*"
      - "--log-level=debug"

    ports:
      - "9555:9555"
    volumes:
      - ./scripts:/usr/src/app/scripts
      - ./data:/usr/src/app/data
      - ./plot:/usr/src/app/plot

    tty: true
